# 🚀 Complete Tensor Indexing & Slicing Guide for Deep Learning

**From Python Lists → NumPy → PyTorch across ALL Architectures**

Master indexing patterns used in:
- **ANN** (Dense networks): `(batch, features)`
- **CNN** (Images): `(batch, channels, height, width)`
- **RNN/LSTM/GRU** (Sequences): `(batch, time, hidden)`
- **Seq2Seq** (Encoder-Decoder): `(batch, seq_len, vocab)`
- **Transformer** (Attention): `(batch, heads, seq, seq)`

---

## SECTION 0: Concept Overview

### Why Learn Indexing?
- **Training:** Load batches, compute losses, backpropagate gradients
- **Inference:** Extract predictions, decode sequences token-by-token
- **Debugging:** Inspect individual samples and their representations

### Three Mental Models (Stack them!)
1. **Lists** (Python): `x[start:stop:step]` - basic slicing
2. **Arrays** (NumPy): extend slicing to N dimensions
3. **Tensors** (PyTorch): same as NumPy + GPU + automatic differentiation

### Shape Notation Key
```
(batch, time, features)      ← 3D tensor
  ↓      ↓      ↓
batch: how many samples process in parallel
time:  how many timesteps/positions in sequence
features: dimension per position (hidden size, vocab size, etc.)
```

---

## SECTION 1: Python Lists (Foundation)

### What: Basic Slicing Syntax
**`list[start:stop:step]`**
- `start`: begin index (inclusive, default=0)
- `stop`: end index (EXCLUSIVE, default=len)
- `step`: interval (default=1)
- Negative indices count from end: `-1` = last element

### Why: Every indexing operation you'll see traces back to this

### Where: Used in
- Batch extraction: `data[0:32]` get first 32 samples
- Sequence manipulation: `seq[:-1]` remove last token
- Data augmentation: `seq[::-1]` reverse sequence

In [17]:
# Python List Slicing - Foundation of Everything
lst = [10, 11, 12, 13, 14]

print("Basic Slicing:")
print(f"Original list: lst = {lst}")
print(f"lst[0]       = {lst[0]}           # first element")
print(f"lst[-1]      = {lst[-1]}          # last element")
print(f"lst[1:4]     = {lst[1:4]}         # elements at indices 1,2,3 (not 4!)")
print(f"lst[:3]      = {lst[:3]}          # first 3 elements")
print(f"lst[2:]      = {lst[2:]}          # from index 2 to end")
print(f"lst[::2]     = {lst[::2]}         # every 2nd element")
print(f"lst[::-1]    = {lst[::-1]}        # reversed")
print()

print("Real-world examples in Deep Learning:")
print("- Training loop: data[i*batch_size:(i+1)*batch_size]  # extract batch")
print("- Teacher forcing: inputs = seq[:-1], targets = seq[1:]  # shift for supervision")
print("- Validation: val_indices = range(len(data))[train_size:]  # holdout split")

Basic Slicing:
Original list: lst = [10, 11, 12, 13, 14]
lst[0]       = 10           # first element
lst[-1]      = 14          # last element
lst[1:4]     = [11, 12, 13]         # elements at indices 1,2,3 (not 4!)
lst[:3]      = [10, 11, 12]          # first 3 elements
lst[2:]      = [12, 13, 14]          # from index 2 to end
lst[::2]     = [10, 12, 14]         # every 2nd element
lst[::-1]    = [14, 13, 12, 11, 10]        # reversed

Real-world examples in Deep Learning:
- Training loop: data[i*batch_size:(i+1)*batch_size]  # extract batch
- Teacher forcing: inputs = seq[:-1], targets = seq[1:]  # shift for supervision
- Validation: val_indices = range(len(data))[train_size:]  # holdout split


---

## SECTION 2: NumPy Arrays (Extend to Multiple Dimensions)

### What: Same slicing rules but for N-dimensional arrays
Shape notation: `(dim0, dim1, dim2, ...)`

### Why: 
- Preprocess data (images as arrays, sequences as arrays)
- Load batches efficiently
- Extract features before feeding to neural networks

### Where: Used in
- Image loading: `image[100:150, 50:100, 0]` crop + select channel
- Batch preparation: `X[train_indices, :]` get training samples
- Feature extraction: `features[:, important_features]` select columns

In [20]:
import numpy as np

# Create 3D array: (batch=2, height=3, width=4)
A = np.arange(2*3*4).reshape(2, 3, 4)
print("Array shape (2, 3, 4):")
print(A)
print()

print("Indexing Examples:")
print(f"A[0].shape        = {A[0].shape}      # first batch (3, 4)")
print(f"Array A[0]:\n{A[0]}\n")
print(f"A[0, 1].shape     = {A[0, 1].shape}     # batch 0, row 1: (4,)")
print(f"A[0, 1, 2]        = {A[0, 1, 2]}        # batch 0, row 1, col 2: scalar")
print(f"A[:, 1, :].shape  = {A[:, 1, :].shape}  # all batches, row 1: (2, 4)")
print(f"A[:, 1, :]:\n{A[:, 1, :]}\n")
print(f"A[:, :, -1].shape = {A[:, :, -1].shape} # all batches, last column: (2, 3)")
print(f"A[:, :, -1]:\n{A[:, :, -1]}\n")
print(f"A[..., -1].shape  = {A[..., -1].shape}  # same as above using ellipsis")
print(f"A[..., -1]:\n{A[..., -1]}\n")
print()

print("Range slicing:")
print(f"A[:, :2, :2].shape = {A[:, :2, :2].shape}  # first 2x2 patch: (2, 2, 2)")
print()
print("Boolean masking:")
mask = A % 2 == 0
print(f"Even elements count: {mask.sum()}")
print(f"First 5 even values: {A[mask][:5]}")

Array shape (2, 3, 4):
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

Indexing Examples:
A[0].shape        = (3, 4)      # first batch (3, 4)
Array A[0]:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

A[0, 1].shape     = (4,)     # batch 0, row 1: (4,)
A[0, 1, 2]        = 6        # batch 0, row 1, col 2: scalar
A[:, 1, :].shape  = (2, 4)  # all batches, row 1: (2, 4)
A[:, 1, :]:
[[ 4  5  6  7]
 [16 17 18 19]]

A[:, :, -1].shape = (2, 3) # all batches, last column: (2, 3)
A[:, :, -1]:
[[ 3  7 11]
 [15 19 23]]

A[..., -1].shape  = (2, 3)  # same as above using ellipsis
A[..., -1]:
[[ 3  7 11]
 [15 19 23]]


Range slicing:
A[:, :2, :2].shape = (2, 2, 2)  # first 2x2 patch: (2, 2, 2)

Boolean masking:
Even elements count: 12
First 5 even values: [0 2 4 6 8]


### 2D Array Pattern: ANN Input
```
X.shape = (batch=32, features=784)
  Row 0: [pixel1, pixel2, ..., pixel784]  ← sample 0
  Row 1: [pixel1, pixel2, ..., pixel784]  ← sample 1
  ...
  Row 31: [...]

Indexing: X[i, j] = sample i's feature j
```

### 3D Array Pattern: RNN/Seq2Seq
```
X.shape = (batch=8, seq_len=50, hidden=256)
  [sample 0: [[t0_feat0, t0_feat1, ...],      ← t=0
              [t1_feat0, t1_feat1, ...],      ← t=1
              ...],
   sample 1: [[...], [...], ...],
   ...]

Indexing: X[b, t, h] = sample b's feature at time t
```

---

## SECTION 3: PyTorch Tensors (GPU + Gradients)

### What: Same as NumPy but with GPU support and automatic differentiation
**`torch.Tensor`** is the standard for deep learning

### Why:
- GPU acceleration: 100x faster on NVIDIA GPUs
- Automatic gradients: `loss.backward()` computes ∇ for you
- Deep integration with neural network libraries

### Where: All your models use this
- Forward pass: `logits = model(input)` returns PyTorch tensor
- Loss computation: `loss = criterion(logits, targets)`
- Backprop: gradients computed on PyTorch tensors

In [22]:
import torch

# Create tensor: (batch=2, time=5, vocab=10)
logits = torch.randn(2, 5, 10)
print(f"logits.shape = {logits.shape}")
print()
print(logits)
print()
print("PyTorch Indexing (same as NumPy):")
print(f"logits[0].shape       = {logits[0].shape}       # first batch: (5, 10)")
print(f"logits[:, 2, :].shape = {logits[:, 2, :].shape} # all batch, time=2: (2, 10)")
print(f"logits[:, :, 5].shape = {logits[:, :, 5].shape} # all batch/time, vocab=5: (2, 5)")
print()

print("Argmax to get token predictions:")
tokens = logits.argmax(dim=2)  # best vocab per timestep
print(f"tokens.shape = {tokens.shape}  # (2, 5) - token per time step")
print(f"tokens = {tokens}")
print()

print("Real Seq2Seq scenario:")
targets = torch.arange(2*5).reshape(2, 5) % 10  # fake target tokens
print(f"targets.shape = {targets.shape}")
print(f"targets = {targets}")
print()

# Reshape for loss (CrossEntropyLoss needs (N, C) not (batch, time, C))
logits_flat = logits.reshape(-1, 10)      # (10, 10) = (batch*time, vocab)
targets_flat = targets.reshape(-1)        # (10,) = (batch*time,)
print(f"After reshape for loss computation:")
print(f"logits_flat.shape  = {logits_flat.shape}")
print(f"targets_flat.shape = {targets_flat.shape}")

logits.shape = torch.Size([2, 5, 10])

tensor([[[ 0.0761, -1.0667,  0.8995,  0.0883, -1.1413, -0.2749,  0.2849,
           0.1230,  0.7582, -0.3187],
         [-0.9968,  1.4641, -0.7518, -0.0999,  1.1375,  0.9930, -2.2547,
           0.4055, -1.1677,  0.0264],
         [-1.7402, -0.8221, -0.4678,  1.1496, -1.9136, -1.1540, -0.1769,
           0.4162, -0.2505,  0.8826],
         [-1.9315, -0.9520,  0.9917,  0.9765,  0.2820,  1.5582, -0.1205,
          -0.7226, -0.5065,  0.6002],
         [-2.1641, -0.5053, -1.1224, -1.7005, -0.1520, -0.5210, -0.1782,
           1.1223, -0.7763, -0.3894]],

        [[ 0.1289,  2.1010,  1.1848,  0.6832,  0.1190, -0.3506,  0.7557,
          -0.8110, -1.1865, -0.0641],
         [ 1.4803,  0.7393,  1.2105, -0.0853, -0.0061,  1.6924, -0.7216,
           0.8889, -0.1620, -1.0572],
         [ 1.8194,  3.4209,  0.1547,  0.1389, -1.3578, -0.6059,  1.8113,
          -0.4743, -0.1222,  1.2391],
         [-1.3419, -2.2105, -1.0221, -0.7443, -1.3896,  0.7736, -0.8980

---

## SECTION 4: PyTorch Dimension Tricks

### What: Four operations to reshape tensors
1. **`unsqueeze(dim)`**: Add a dimension of size 1
2. **`squeeze(dim)`**: Remove dimension of size 1
3. **`reshape(shape)` / `view(shape)`**: Change shape
4. **`permute(dims)`**: Rearrange dimension order

### Why: Layers expect specific shapes
- LSTM: input must be `(batch, seq, features)` not `(batch, seq)`
- Loss: needs `(N, C)` not `(batch, time, C)`
- CNN→Dense: flatten spatial dims: `(batch, C, H, W)` → `(batch, C*H*W)`

### Where: Everywhere in real code

In [25]:
import torch

print("="*60)
print("DIMENSION TRICKS: unsqueeze, squeeze, reshape, permute")
print("="*60)
print()

# Starting tensor
x = torch.randn(2, 3)  # (batch=2, features=3)
print(f"x.shape = {x.shape}")
print()
print(x)
print()
print("1️⃣  UNSQUEEZE (add dimension):")
print(f"x.unsqueeze(0).shape  = {x.unsqueeze(0).shape}   # (1, 2, 3) - add at start")
print(x.unsqueeze(0))
print(f"x.unsqueeze(1).shape  = {x.unsqueeze(1).shape}   # (2, 1, 3) - add in middle")
print(x.unsqueeze(1))
print(f"x.unsqueeze(2).shape  = {x.unsqueeze(2).shape}   # (2, 3, 1) - add at end")
print(f"x.unsqueeze(-1).shape = {x.unsqueeze(-1).shape}  # (2, 3, 1) - add at end (alternate)")
print(x.unsqueeze(-1))
print()

print("2️⃣  SQUEEZE (remove dimension of size 1):")
y = x.unsqueeze(1)  # now (2, 1, 3)
print(f"y.shape = {y.shape}")
print(y)
print(f"y.squeeze().shape = {y.squeeze().shape}       # (2, 3) - remove all size-1 dims")
print(y.squeeze())
print(f"y.squeeze(1).shape = {y.squeeze(1).shape}     # (2, 3) - remove dim 1 specifically")
print(y.squeeze(1))
print()

print("3️⃣  RESHAPE (change shape):")
z = torch.arange(2*3*4).reshape(2, 3, 4)  # (2, 3, 4)
print(f"z.shape = {z.shape}")
print(f"z.reshape(6, 4).shape = {z.reshape(6, 4).shape}     # flatten batch/time")
print(f"z.reshape(-1, 4).shape = {z.reshape(-1, 4).shape}   # -1 means 'infer this dim'")
print(f"z.reshape(2, 12).shape = {z.reshape(2, 12).shape}   # keep batch, flatten rest")
print()

print("4️⃣  PERMUTE (rearrange dimensions):")
print(f"z.shape = {z.shape}  # (2, 3, 4) = (batch, time, features)")
print(f"z.permute(0, 2, 1).shape = {z.permute(0, 2, 1).shape}  # (batch, features, time)")
print(f"z.permute(2, 0, 1).shape = {z.permute(2, 0, 1).shape}  # (features, batch, time)")
print()

print("5️⃣  VIEW vs RESHAPE (same result, view requires contiguous):")
print(f"z.view(6, 4).shape = {z.view(6, 4).shape}")
print(f"z.reshape(6, 4).shape = {z.reshape(6, 4).shape}")
print("view fails if tensor is non-contiguous (e.g., after permute)")

DIMENSION TRICKS: unsqueeze, squeeze, reshape, permute

x.shape = torch.Size([2, 3])

tensor([[ 0.2135,  0.9987,  2.9061],
        [-0.6749, -2.0914, -1.5020]])

1️⃣  UNSQUEEZE (add dimension):
x.unsqueeze(0).shape  = torch.Size([1, 2, 3])   # (1, 2, 3) - add at start
tensor([[[ 0.2135,  0.9987,  2.9061],
         [-0.6749, -2.0914, -1.5020]]])
x.unsqueeze(1).shape  = torch.Size([2, 1, 3])   # (2, 1, 3) - add in middle
tensor([[[ 0.2135,  0.9987,  2.9061]],

        [[-0.6749, -2.0914, -1.5020]]])
x.unsqueeze(2).shape  = torch.Size([2, 3, 1])   # (2, 3, 1) - add at end
x.unsqueeze(-1).shape = torch.Size([2, 3, 1])  # (2, 3, 1) - add at end (alternate)
tensor([[[ 0.2135],
         [ 0.9987],
         [ 2.9061]],

        [[-0.6749],
         [-2.0914],
         [-1.5020]]])

2️⃣  SQUEEZE (remove dimension of size 1):
y.shape = torch.Size([2, 1, 3])
tensor([[[ 0.2135,  0.9987,  2.9061]],

        [[-0.6749, -2.0914, -1.5020]]])
y.squeeze().shape = torch.Size([2, 3])       # (2, 3) - remo

### Real Seq2Seq Decoder Example
```python
# One token at a time during decoding
token_id = 42              # (,) scalar token
token_id = token_id.unsqueeze(0)  # (1,) for embedding
embed = embedding(token_id)       # (1, embed_dim) from embedding table
embed = embed.unsqueeze(1)        # (1, 1, embed_dim) - LSTM needs time dim!
output, (h, c) = lstm(embed, (h, c))  # (1, 1, hidden) output
output = output.squeeze(1)        # (1, hidden) - remove time dim
logits = fc_layer(output)         # (1, vocab) - get predictions
```

---

## SECTION 5: Cat vs Stack (Critical Difference)

### What:
- **`torch.cat()`**: Join along **existing** dimension
- **`torch.stack()`**: Create **new** dimension

### Why: Different data structures need different operations
- **cat**: More of the same (more samples, more timesteps)
- **stack**: Group variants (ensemble predictions, multi-model outputs)

### Where: Used in
- **cat**: Batch loading, bidirectional RNNs, concatenating features
- **stack**: Building outputs over time, ensemble averaging

In [26]:
import torch

print("="*60)
print("CAT vs STACK")
print("="*60)
print()

a = torch.ones(2, 3)
b = torch.zeros(2, 3)
print(f"a.shape = {a.shape}")
print(f"b.shape = {b.shape}")
print()

print("torch.cat() - Join along existing dimension:")
cat_dim0 = torch.cat([a, b], dim=0)
print(f"cat([a, b], dim=0).shape = {cat_dim0.shape}  # (4, 3) - more rows")
print("[[1, 1, 1],")
print(" [1, 1, 1],  ← batch doubled!")
print(" [0, 0, 0],")
print(" [0, 0, 0]]")
print()

cat_dim1 = torch.cat([a, b], dim=1)
print(f"cat([a, b], dim=1).shape = {cat_dim1.shape}  # (2, 6) - more columns")
print("[[1, 1, 1, 0, 0, 0],  ← features doubled!")
print(" [1, 1, 1, 0, 0, 0]]")
print()
print()

print("torch.stack() - Create new dimension:")
stack_dim0 = torch.stack([a, b], dim=0)
print(f"stack([a, b], dim=0).shape = {stack_dim0.shape}  # (2, 2, 3) - new batch dim")
print()

stack_dim1 = torch.stack([a, b], dim=1)
print(f"stack([a, b], dim=1).shape = {stack_dim1.shape}  # (2, 2, 3) - new middle dim")
print()

stack_dim2 = torch.stack([a, b], dim=2)
print(f"stack([a, b], dim=2).shape = {stack_dim2.shape}  # (2, 3, 2) - new last dim")

CAT vs STACK

a.shape = torch.Size([2, 3])
b.shape = torch.Size([2, 3])

torch.cat() - Join along existing dimension:
cat([a, b], dim=0).shape = torch.Size([4, 3])  # (4, 3) - more rows
[[1, 1, 1],
 [1, 1, 1],  ← batch doubled!
 [0, 0, 0],
 [0, 0, 0]]

cat([a, b], dim=1).shape = torch.Size([2, 6])  # (2, 6) - more columns
[[1, 1, 1, 0, 0, 0],  ← features doubled!
 [1, 1, 1, 0, 0, 0]]


torch.stack() - Create new dimension:
stack([a, b], dim=0).shape = torch.Size([2, 2, 3])  # (2, 2, 3) - new batch dim

stack([a, b], dim=1).shape = torch.Size([2, 2, 3])  # (2, 2, 3) - new middle dim

stack([a, b], dim=2).shape = torch.Size([2, 3, 2])  # (2, 3, 2) - new last dim


### Seq2Seq Autoregressive Generation Example
```python
# Build output token-by-token (decoder generates one prediction per step)
outputs = []  # will collect predictions at each timestep

for t in range(max_time):
    logits_t = decoder(input_t, hidden)  # (batch, vocab) for time t
    outputs.append(logits_t)  # list of (batch, vocab) tensors
    hidden = update_hidden(logits_t)  # update hidden state

# Stack all timesteps: [(batch, vocab), ...] → (batch, time, vocab)
all_outputs = torch.stack(outputs, dim=1)  # (batch, time, vocab) ✓

# If we cat instead, wrong!
wrong = torch.cat(outputs, dim=1)  # (batch, vocab*time) ✗
```

---

## SECTION 6: Time Step & Batch Selection (Decoding Loops)

### What: Extract specific samples/timesteps from batched tensors
**Keep batch dimension intact** - this is key!

### Why: Core in training and especially inference
- **Training:** Sample specific batches for debugging
- **Inference:** Decode one timestep at a time
- **Debugging:** Inspect individual predictions

### Where: Used in

In [27]:
import torch

print("="*60)
print("TIME STEP & BATCH SELECTION")
print("="*60)
print()

# Seq2Seq decoder output: (batch=4, time=6, vocab=10)
logits = torch.randn(4, 6, 10)
print(f"logits.shape = {logits.shape}  # (batch=4, time=6, vocab=10)")
print()

print("Getting specific timesteps (decoder loop):")
t = 2
logits_at_t = logits[:, t, :]  # all batches at time t
print(f"logits[:, {t}, :].shape = {logits_at_t.shape}  # (4, 10) - all batch at time {t}")
print()

print("Getting specific batch:")
b = 1
logits_batch_b = logits[b, :, :]  # sample b, all times
print(f"logits[{b}, :, :].shape = {logits_batch_b.shape}  # (6, 10) - sample {b} full sequence")
print()

print("Getting specific batch AND timestep:")
logits_single = logits[b, t, :]  # sample b, time t
print(f"logits[{b}, {t}, :].shape = {logits_single.shape}  # (10,) - sample {b} at time {t}")
print()

print("Argmax to get predicted tokens:")
token_ids = logits.argmax(dim=2)  # best vocab per timestep
print(f"token_ids.shape = {token_ids.shape}  # (4, 6) - token per batch per time")
print(f"token_ids = {token_ids}")
print()

print("Teacher forcing next input:")
time_step = 1
teacher_next = token_ids[:, time_step]  # get predictions at time_step
print(f"teacher_next.shape = {teacher_next.shape}  # (4,) - one token per batch")
print(f"teacher_next = {teacher_next}  ← use as next decoder input")

TIME STEP & BATCH SELECTION

logits.shape = torch.Size([4, 6, 10])  # (batch=4, time=6, vocab=10)

Getting specific timesteps (decoder loop):
logits[:, 2, :].shape = torch.Size([4, 10])  # (4, 10) - all batch at time 2

Getting specific batch:
logits[1, :, :].shape = torch.Size([6, 10])  # (6, 10) - sample 1 full sequence

Getting specific batch AND timestep:
logits[1, 2, :].shape = torch.Size([10])  # (10,) - sample 1 at time 2

Argmax to get predicted tokens:
token_ids.shape = torch.Size([4, 6])  # (4, 6) - token per batch per time
token_ids = tensor([[2, 9, 8, 2, 1, 4],
        [9, 3, 2, 2, 0, 0],
        [3, 6, 0, 8, 1, 9],
        [6, 0, 9, 8, 5, 1]])

Teacher forcing next input:
teacher_next.shape = torch.Size([4])  # (4,) - one token per batch
teacher_next = tensor([9, 3, 6, 0])  ← use as next decoder input


### Real Seq2Seq Decoding Pattern
```python
logits = model(src_ids, tgt_ids)  # (batch, tgt_len, vocab)

# Autoregressive: one word at a time
for t in range(tgt_len):
    current_step = logits[:, t, :]    # (batch, vocab) - preds at step t
    tokens_t = current_step.argmax(dim=1)  # (batch,) - best token per sample
    
    if (tokens_t == EOS_ID).any():
        print("Some samples finished!")
```

---

## SECTION 7: Masking & Padding (Critical for Training)

### What: Create boolean masks to ignore PAD tokens
**Paddings are fake, don't let them ruin your training!**

### Why: Deep models must ignore padding
- Padding tokens are just fillers to make sequences same length
- Loss should NOT penalize predictions on padding
- Attention should NOT focus on paddings
- RNN should take hidden state at actual sequence end, not at padding

### Where: Used in

In [28]:
import torch
import torch.nn as nn
import torch.nn.functional as F

print("="*60)
print("MASKING & PADDING: The Right Way")
print("="*60)
print()

# Targets with padding
targets = torch.tensor([[1, 2, 3, 0, 0],     # 3 real tokens, 2 pads
                        [4, 5, 0, 0, 0]])    # 2 real tokens, 3 pads
PAD_ID = 0
print(f"targets = {targets}  (0 = PAD)")
print()

print("1️⃣  Loss Masking (Seq2Seq):")
logits = torch.randn(2, 5, 100)  # (batch, time, vocab)
loss_fn = nn.CrossEntropyLoss(reduction='none')

# Flat for loss computation
L = loss_fn(logits.reshape(-1, 100), targets.reshape(-1))  # (10,)
print(f"Loss computed: {L.shape}")

# Create mask
pad_mask = targets.reshape(-1) == PAD_ID  # (10,) bool
print(f"pad_mask: {pad_mask}")

# Apply mask
L[pad_mask] = 0  # zero out PAD losses
final_loss = L.sum() / (~pad_mask).sum()  # avg only real tokens
print(f"Final loss (ignoring pads): {final_loss:.4f}")
print()

print("2️⃣  Attention Masking (Transformer):")
# Prevent attention to padded positions
attn_scores = torch.randn(2, 4, 5, 5)  # (batch, heads, seq, seq)
seq_mask = torch.tensor([1, 1, 1, 0, 0], dtype=torch.bool)  # which are real
# Expand mask for broadcasting
seq_mask_2d = seq_mask.unsqueeze(0).unsqueeze(0).unsqueeze(0)  # (1, 1, 1, 5)
attn_scores.masked_fill_(~seq_mask_2d, float('-inf'))
print(f"Attention scores masked (padded positions set to -inf)")
print()

print("3️⃣  RNN Output Masking (Get hidden at actual end):")
batch_size, seq_len, hidden_dim = 2, 5, 4
rnn_outputs = torch.randn(batch_size, seq_len, hidden_dim)
actual_lengths = torch.tensor([3, 2])  # real sequence lengths

# ❌ Wrong: use last timestep (includes padding)
wrong = rnn_outputs[:, -1, :]
print(f"❌ Last timestep (includes padding): {wrong.shape}")

# ✓ Right: use actual last timestep
correct = rnn_outputs[range(batch_size), actual_lengths - 1, :]
print(f"✓ Actual last timestep (no padding): {correct.shape}")
print(f"Batch 0: used timestep {actual_lengths[0].item()} (real)")
print(f"Batch 1: used timestep {actual_lengths[1].item()} (real)")

MASKING & PADDING: The Right Way

targets = tensor([[1, 2, 3, 0, 0],
        [4, 5, 0, 0, 0]])  (0 = PAD)

1️⃣  Loss Masking (Seq2Seq):
Loss computed: torch.Size([10])
pad_mask: tensor([False, False, False,  True,  True, False, False,  True,  True,  True])
Final loss (ignoring pads): 5.0860

2️⃣  Attention Masking (Transformer):
Attention scores masked (padded positions set to -inf)

3️⃣  RNN Output Masking (Get hidden at actual end):
❌ Last timestep (includes padding): torch.Size([2, 4])
✓ Actual last timestep (no padding): torch.Size([2, 4])
Batch 0: used timestep 3 (real)
Batch 1: used timestep 2 (real)


---

## SECTION 8: Broadcasting (Automatic Shape Expansion)

### What: Smaller tensors auto-expand to match larger ones
**No copying - just reuse the same data multiple times!**

### Why: Save memory, write cleaner code
- Element-wise ops require same shapes
- Broadcasting does the expansion for you
- Much faster than manual loops

### Broadcasting Rules (Remember these!):
1. Compare dimensions from RIGHT to LEFT
2. Dimensions must match OR one must be 1 (or not exist)
3. The size-1 dimension broadcasts to match the larger

In [29]:
import torch

print("="*60)
print("BROADCASTING: Auto Shape Expansion")
print("="*60)
print()

print("1️⃣  ANN - Add Bias:")
logits = torch.randn(32, 10)   # (batch, vocab)
bias = torch.randn(10)          # (vocab,)
output = logits + bias          # bias broadcasts to (32, 10)
print(f"logits.shape: {logits.shape}")
print(f"bias.shape:   {bias.shape}  → broadcasts to (32, 10)")
print(f"output.shape: {output.shape}")
print()

print("2️⃣  CNN - Batch Norm Affine:")
x = torch.randn(16, 3, 224, 224)  # (batch, channels, H, W)
gamma = torch.randn(3)  # (channels,) scale
beta = torch.randn(3)   # (channels,) shift

# Reshape for broadcasting
gamma_reshaped = gamma.view(1, 3, 1, 1)  # (1, 3, 1, 1)
beta_reshaped = beta.view(1, 3, 1, 1)    # (1, 3, 1, 1)
normalized = (x * gamma_reshaped) + beta_reshaped

print(f"x.shape:           {x.shape}")
print(f"gamma.shape:       {gamma.shape}  → reshape to (1, 3, 1, 1)")
print(f"normalized.shape:  {normalized.shape}")
print()

print("3️⃣  Transformer - Attention Mask:")
attn_scores = torch.randn(2, 4, 5, 5)  # (batch, heads, seq, seq)
mask = torch.ones(5, 5)  # (seq, seq) - same for all batches/heads
mask_expanded = mask.unsqueeze(0).unsqueeze(0)  # (1, 1, 5, 5)
masked_scores = attn_scores + mask_expanded  # broadcasts!

print(f"attn_scores.shape:  {attn_scores.shape}")
print(f"mask.shape:         {mask.shape}  → unsqueeze to (1, 1, 5, 5)")
print(f"result.shape:       {masked_scores.shape}")
print()

print("4️⃣  Seq2Seq - Loss Weighting:")
loss = torch.randn(8, 15)  # (batch, seq_len)
weights = torch.tensor([[2.0], [1.0], [1.0], [1.0],
                        [1.5], [1.5], [1.0], [1.0]])  # (batch, 1)
weighted_loss = loss * weights  # weights broadcast to (8, 15)

print(f"loss.shape:          {loss.shape}")
print(f"weights.shape:       {weights.shape}  → broadcasts to (8, 15)")
print(f"weighted_loss.shape: {weighted_loss.shape}")
print(f"Batch 0's weight {weights[0, 0].item():.1f} applied to all 15 timesteps")

BROADCASTING: Auto Shape Expansion

1️⃣  ANN - Add Bias:
logits.shape: torch.Size([32, 10])
bias.shape:   torch.Size([10])  → broadcasts to (32, 10)
output.shape: torch.Size([32, 10])

2️⃣  CNN - Batch Norm Affine:
x.shape:           torch.Size([16, 3, 224, 224])
gamma.shape:       torch.Size([3])  → reshape to (1, 3, 1, 1)
normalized.shape:  torch.Size([16, 3, 224, 224])

3️⃣  Transformer - Attention Mask:
attn_scores.shape:  torch.Size([2, 4, 5, 5])
mask.shape:         torch.Size([5, 5])  → unsqueeze to (1, 1, 5, 5)
result.shape:       torch.Size([2, 4, 5, 5])

4️⃣  Seq2Seq - Loss Weighting:
loss.shape:          torch.Size([8, 15])
weights.shape:       torch.Size([8, 1])  → broadcasts to (8, 15)
weighted_loss.shape: torch.Size([8, 15])
Batch 0's weight 2.0 applied to all 15 timesteps


---

## SECTION 9: NumPy Fundamentals (Data Preparation)

### What: Core NumPy operations for preprocessing
You'll use these to load and prepare data BEFORE feeding to PyTorch

### Where: Used in

In [30]:
import numpy as np

print("="*60)
print("NUMPY FUNDAMENTALS")
print("="*60)
print()

print("Creation:")
A = np.array([[1, 2], [3, 4]], dtype=np.float32)
Z = np.zeros((2, 3))
O = np.ones((2, 3))
R = np.arange(6).reshape(2, 3)  # 0..5 reshaped
print(f"A:\n{A}")
print(f"R shape {R.shape}:\n{R}")
print()

print("Reshape/Flatten:")
R_flat = R.reshape(-1)  # -1 means infer
print(f"R.reshape(-1): {R_flat}")
print(f"R.T (transpose): shape {R.T.shape}")
print()

print("Combining:")
A1 = np.ones((2, 3))
A2 = np.zeros((2, 3))
cat_result = np.concatenate([A1, A2], axis=0)  # stack vertically
print(f"concatenate axis=0: {cat_result.shape}")
stack_result = np.stack([A1, A2], axis=0)  # group
print(f"stack axis=0: {stack_result.shape}")
print()

print("Reductions:")
print(f"R.sum(): {R.sum()}")
print(f"R.sum(axis=0): {R.sum(axis=0)}")
print(f"R.max(axis=1): {R.max(axis=1)}")
print()

print("Broadcasting:")
X = np.array([[1., 2., 3.], [4., 5., 6.]])  # (2, 3)
bias = np.array([10., 20., 30.])  # (3,)
result = X + bias  # broadcasts bias to (2, 3)
print(f"X shape: {X.shape}")
print(f"bias shape: {bias.shape} → broadcasts")
print(f"X + bias:\n{result}")
print()

print("Boolean Masking:")
mask = X > 3
print(f"X > 3:\n{mask}")
print(f"X[mask]: {X[mask]}  (only values > 3)")
print()

print("Type conversion:")
int_arr = np.array([1, 2, 3], dtype=np.int64)
float_arr = int_arr.astype(np.float32)
print(f"int dtype: {int_arr.dtype}")
print(f"float dtype: {float_arr.dtype}  (good for PyTorch!)")

NUMPY FUNDAMENTALS

Creation:
A:
[[1. 2.]
 [3. 4.]]
R shape (2, 3):
[[0 1 2]
 [3 4 5]]

Reshape/Flatten:
R.reshape(-1): [0 1 2 3 4 5]
R.T (transpose): shape (3, 2)

Combining:
concatenate axis=0: (4, 3)
stack axis=0: (2, 2, 3)

Reductions:
R.sum(): 15
R.sum(axis=0): [3 5 7]
R.max(axis=1): [2 5]

Broadcasting:
X shape: (2, 3)
bias shape: (3,) → broadcasts
X + bias:
[[11. 22. 33.]
 [14. 25. 36.]]

Boolean Masking:
X > 3:
[[False False False]
 [ True  True  True]]
X[mask]: [4. 5. 6.]  (only values > 3)

Type conversion:
int dtype: int64
float dtype: float32  (good for PyTorch!)


---

## SECTION 10: Architecture-Specific Deep Dives

Now that you understand indexing fundamentals, let's see how each architecture uses these patterns.

### 10.1: ANN (Fully Connected Networks)
Shape: `(batch, features)` → `(batch, hidden)` → `(batch, classes)`

**Key indexing patterns:**
- Batch: `x[i, :]` get sample i
- Features: `x[:, j]` get feature j across batch
- Classes: `logits[:, c]` get probability of class c

In [31]:
import torch
import torch.nn as nn

print("="*60)
print("ANN (Dense Networks) - Indexing Patterns")
print("="*60)
print()

# Input: 32 images, 784 pixels each (28x28 MNIST flattened)
x = torch.randn(32, 784)     # (batch, input_features)
print(f"Input x.shape: {x.shape}")

# Forward pass
fc1 = nn.Linear(784, 128)
fc2 = nn.Linear(128, 10)     # 10 classes

h = torch.relu(fc1(x))       # (32, 128)
logits = fc2(h)              # (32, 10)
print(f"Hidden.shape: {h.shape}")
print(f"Logits.shape: {logits.shape}")
print()

print("Key indexing operations:")
print(f"Sample 0 logits: {logits[0].shape}  # (10,) all class scores for sample 0")
print(f"Class 5 scores: {logits[:, 5].shape}  # (32,) class 5 score for all samples")
print()

# Predictions
probs = torch.softmax(logits, dim=1)  # (32, 10)
predictions = probs.argmax(dim=1)     # (32,) best class per sample
print(f"Predictions: {predictions.shape}  values: {predictions[:5]}")
print()

# Loss
targets = torch.randint(0, 10, (32,))
loss_fn = nn.CrossEntropyLoss()
loss = loss_fn(logits, targets)
print(f"Loss: {loss.item():.4f}")

ANN (Dense Networks) - Indexing Patterns

Input x.shape: torch.Size([32, 784])
Hidden.shape: torch.Size([32, 128])
Logits.shape: torch.Size([32, 10])

Key indexing operations:
Sample 0 logits: torch.Size([10])  # (10,) all class scores for sample 0
Class 5 scores: torch.Size([32])  # (32,) class 5 score for all samples

Predictions: torch.Size([32])  values: tensor([5, 6, 2, 4, 6])

Loss: 2.3720


### 10.2: CNN (Convolutional Networks)
Shape: `(batch, channels, height, width)` → `(batch, filters, H', W')`

**Key indexing patterns:**
- Channel: `x[:, c, :, :]` get channel c
- Spatial: `x[:, :, h:h+k, w:w+k]` get patch
- Pixel: `x[:, :, h, w]` get all channels at pixel (h, w)

In [ ]:
import torch
import torch.nn as nn

print("="*60)
print("CNN (Images) - Indexing Patterns")
print("="*60)
print()

# Input: 8 RGB images, 224x224
x = torch.randn(8, 3, 224, 224)  # (batch, channels, height, width)
print(f"Input x.shape: {x.shape}")
print()

# Forward pass
conv1 = nn.Conv2d(3, 64, kernel_size=3, padding=1)
pool = nn.MaxPool2d(2)

x = conv1(x)         # (8, 64, 224, 224)
x = torch.relu(x)
x = pool(x)          # (8, 64, 112, 112)
print(f"After conv+pool: {x.shape}")
print()

print("Key indexing operations:")
print(f"Channel 0: {x[:, 0, :, :].shape}  # (8, 112, 112) - first filter's output")
print(f"RGB channels (input): {x.shape}  # all 3 color channels")
print(f"Pixel at (50, 50): {x[:, :, 50, 50].shape}  # (8, 64) - all filters at that pixel")
print(f"Patch (50:55, 50:55): {x[:, :, 50:55, 50:55].shape}  # (8, 64, 5, 5) - 5x5 patch")
print()

# Flatten for classification
x_flat = x.reshape(8, -1)  # (8, 64*112*112)
print(f"Flattened: {x_flat.shape}")

fc = nn.Linear(64*112*112, 10)
logits = fc(x_flat)  # (8, 10)
print(f"Logits: {logits.shape}")

### 10.3: RNN/LSTM/GRU (Sequences)
Shape: `(batch, seq_len, input)` → `(batch, seq_len, hidden)` → `(batch, hidden)`

**Key indexing patterns:**
- Time step: `outputs[:, t, :]` all batch at time t
- Final: `outputs[:, -1, :]` final hidden state
- LSTM state: `(h_n, c_n)` both needed for next step

In [ ]:
import torch
import torch.nn as nn

print("="*60)
print("RNN/LSTM/GRU - Indexing Patterns")
print("="*60)
print()

# Input: 16 sequences, length 50, embedding dimension 100
x = torch.randn(16, 50, 100)  # (batch, seq_len, input_dim)
print(f"Input x.shape: {x.shape}")
print()

# LSTM: batch=16, seq_len=50, hidden_dim=256
lstm = nn.LSTM(100, 256, batch_first=True)
outputs, (h_n, c_n) = lstm(x)
print(f"outputs.shape: {outputs.shape}  # (batch, seq_len, hidden)")
print(f"h_n.shape: {h_n.shape}  # (num_layers, batch, hidden)")
print(f"c_n.shape: {c_n.shape}  # cell state")
print()

print("Key indexing operations:")
t = 10
print(f"outputs[:, {t}, :].shape: {outputs[:, t, :].shape}  # all batch at time {t}")
print(f"outputs[:, -1, :].shape: {outputs[:, -1, :].shape}  # final output (or use h_n[0])")
print(f"h_n[0].shape: {h_n[0].shape}  # final hidden state")
print()

# Classification: use final hidden state
final_hidden = outputs[:, -1, :]  # (16, 256) OR h_n[0]
fc = nn.Linear(256, 10)  # 10 classes
logits = fc(final_hidden)  # (16, 10)
print(f"Classification logits: {logits.shape}")
print()

# Variable length sequences: gather at actual end
print("Variable length example:")
actual_lengths = torch.tensor([30, 25, 50, 40, 50, 20, 45, 50,
                               30, 25, 50, 40, 50, 20, 45, 50])
batch_indices = torch.arange(16)
final_correct = outputs[batch_indices, actual_lengths - 1, :]
print(f"Using actual_lengths: {final_correct.shape}  (correct, no padding!)")

### 10.4: Seq2Seq (Encoder-Decoder)
Shape:
- Encoder: `(batch, src_len)` → `(batch, src_len, hidden)` + context `(batch, hidden)`
- Decoder: `(batch, tgt_len)` → `(batch, tgt_len, vocab)`

**Key indexing patterns:**
- Teacher forcing: `logits[:, t, :]` predictions at time t
- Loss: flatten to `(batch*tgt_len, vocab)` before loss
- Inference: argmax over vocab dim

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

print("="*60)
print("SEQ2SEQ (Encoder-Decoder) - Indexing Patterns")
print("="*60)
print()

# Pretend encoder/decoder (for demo)
batch, src_len, tgt_len, vocab = 4, 20, 15, 5000

# Encoder output
enc_outputs = torch.randn(batch, src_len, 256)  # (batch, src_len, hidden)
context = enc_outputs[:, -1, :]  # (batch, hidden) - final state
print(f"enc_outputs.shape: {enc_outputs.shape}")
print(f"context.shape: {context.shape}")
print()

# Decoder output
dec_logits = torch.randn(batch, tgt_len, vocab)  # (batch, tgt_len, vocab)
print(f"dec_logits.shape: {dec_logits.shape}")
print()

print("Training (teacher forcing):")
targets = torch.randint(0, vocab, (batch, tgt_len))

# Reshape for loss
dec_logits_flat = dec_logits.reshape(-1, vocab)  # (batch*tgt_len, vocab)
targets_flat = targets.reshape(-1)  # (batch*tgt_len,)
print(f"logits_flat: {dec_logits_flat.shape}")
print(f"targets_flat: {targets_flat.shape}")

loss_fn = nn.CrossEntropyLoss()
loss = loss_fn(dec_logits_flat, targets_flat)
print(f"Loss: {loss.item():.4f}")
print()

print("Inference (autoregressive decoding):")
print("Generate one token at a time:")
print(f"At timestep t: dec_logits[:, t, :].shape = (4, 5000)")
print(f"Argmax to get token: .argmax(dim=1) → (4,) token per sample")
print()

# Simulate decoding
pred_tokens = dec_logits.argmax(dim=2)  # (batch, tgt_len) all predictions
print(f"All predictions: {pred_tokens.shape}")
print(f"First sequence predictions: {pred_tokens[0]}")

### 10.5: Transformer (Multi-Head Attention)
Shape: `(batch, seq, dim)` → `(batch, heads, seq, seq)` attention → `(batch, seq, dim)`

**Key indexing patterns:**
- Head: `attn[:, h, :, :]` attention for head h
- Position: `attn[:, :, i, :]` what position i attends to
- Mask: broadcast causal mask for autoregressive

In [ ]:
import torch
import torch.nn as nn
import math

print("="*60)
print("TRANSFORMER (Multi-Head Attention) - Indexing Patterns")
print("="*60)
print()

batch, seq_len, d_model, num_heads = 8, 100, 512, 8
head_dim = d_model // num_heads  # 64

print(f"Input: (batch={batch}, seq_len={seq_len}, d_model={d_model})")
print(f"Number of heads: {num_heads}, Head dimension: {head_dim}")
print()

# Q, K, V after projection
Q = torch.randn(batch, seq_len, d_model).view(batch, seq_len, num_heads, head_dim)
Q = Q.transpose(1, 2)  # (batch, heads, seq_len, head_dim)
print(f"Q after reshape & transpose: {Q.shape}")
print()

K = torch.randn(batch, seq_len, d_model).view(batch, seq_len, num_heads, head_dim)
K = K.transpose(1, 2)  # (batch, heads, seq_len, head_dim)

# Attention scores
scores = (Q @ K.transpose(-2, -1)) / math.sqrt(head_dim)  # (batch, heads, seq, seq)
print(f"Attention scores: {scores.shape}  # (batch, heads, seq, seq)")
print()

print("Key indexing operations:")
h = 0
print(f"Head {h} attention matrix: scores[:, {h}, :, :].shape = (8, 100, 100)")
print(f"What position 50 attends to: scores[:, :, 50, :].shape = (8, 8, 100)")
print()

print("Causal masking for decoder (prevent looking at future):")
causal_mask = torch.triu(torch.ones(seq_len, seq_len), diagonal=1).bool()
scores = scores.masked_fill(causal_mask, float('-inf'))
print(f"Applied causal mask (upper triangle = -inf)")
print()

# Softmax
weights = torch.softmax(scores, dim=-1)  # (batch, heads, seq, seq)
print(f"Attention weights: {weights.shape}")

# Apply to values
V = torch.randn(batch, seq_len, d_model).view(batch, seq_len, num_heads, head_dim)
V = V.transpose(1, 2)  # (batch, heads, seq_len, head_dim)

output = weights @ V  # (batch, heads, seq_len, head_dim)
print(f"After attention: {output.shape}")

# Merge heads back
output = output.transpose(1, 2).contiguous()  # (batch, seq, heads, head_dim)
output = output.view(batch, seq_len, d_model)  # (batch, seq, d_model)
print(f"Merged heads: {output.shape}")

---

## SECTION 11: Common Patterns Reference

Quick lookup for patterns you see in real code.

### Pattern 1: Batch Extraction
```python
# Get batch i from dataset
batch_start = i * batch_size
batch_end = (i + 1) * batch_size
X_batch = X[batch_start:batch_end]  # (batch_size, ...)
y_batch = y[batch_start:batch_end]  # (batch_size,)
```

### Pattern 2: Teacher Forcing (Seq2Seq)
```python
# Shift targets: input is all-but-last, target is all-but-first
dec_input = targets[:, :-1]   # remove last token
dec_target = targets[:, 1:]   # remove first token
# Both shape (batch, seq_len-1)
```

### Pattern 3: Loss Reshaping
```python
# Flatten for CrossEntropyLoss
logits = torch.randn(batch, seq, vocab)      # (B, T, V)
targets = torch.randint(0, vocab, (batch, seq))  # (B, T)

logits_flat = logits.reshape(-1, vocab)      # (B*T, V)
targets_flat = targets.reshape(-1)           # (B*T,)

loss = criterion(logits_flat, targets_flat)  # scalar
```

### Pattern 4: Argmax → Next Input
```python
# Get prediction tokens for next step
logits = torch.randn(batch, vocab)  # (B, V)
tokens = logits.argmax(dim=1)       # (B,) best token per sample
# Use tokens as next input to decoder
```

### Pattern 5: Variable Length Handling
```python
# Get final hidden state at actual sequence end (not padding)
rnn_outputs = torch.randn(batch, max_len, hidden)
lengths = torch.tensor([30, 25, 50])  # actual lengths

batch_idx = torch.arange(batch)
final_hidden = rnn_outputs[batch_idx, lengths - 1, :]  # (batch, hidden)
```

### Pattern 6: Padding Mask Application
```python
# Create and apply padding mask
targets = torch.tensor([[1, 2, 3, 0, 0], [4, 5, 0, 0, 0]])
pad_mask = (targets == PAD_ID)  # boolean mask

loss = criterion(logits.reshape(-1, vocab), targets.reshape(-1))
loss = loss.reshape(batch, seq)
loss = loss.masked_fill(pad_mask, 0)  # zero out pad losses
loss = loss.sum() / (~pad_mask).sum()  # average non-pad
```

### Pattern 7: Multi-Head Attention
```python
# Split into heads and process
batch, seq, d_model, num_heads = 8, 100, 512, 8
head_dim = d_model // num_heads

x = torch.randn(batch, seq, d_model)  # (8, 100, 512)
x = x.view(batch, seq, num_heads, head_dim)  # (8, 100, 8, 64)
x = x.transpose(1, 2)  # (8, 8, 100, 64) = (batch, heads, seq, dim_per_head)

# Process each head in parallel
# ...

# Merge heads back
x = x.transpose(1, 2).contiguous()  # (8, 100, 8, 64)
x = x.view(batch, seq, d_model)    # (8, 100, 512)
```

---

## SECTION 12: Practice Exercises

Test your understanding!

### Exercise 1: Create and Slice
```python
import torch

# Create tensor shape (3, 4, 5)
x = torch.randn(3, 4, 5)

# Task: Get all batches, last two time steps, first 2 vocab
# Expected shape: (3, 2, 2)
result = x[:, -2:, :2]
print(f"Result shape: {result.shape}")
```

### Exercise 2: Argmax and Index
```python
# Get token predictions at specific timestep
logits = torch.randn(2, 6, 10)  # (batch, time, vocab)
tokens = logits.argmax(dim=2)   # (2, 6)

# Get predictions at timestep 3 for all batches
tokens_t3 = tokens[:, 3]  # (2,)
print(f"Tokens at t=3: {tokens_t3}")
```

### Exercise 3: Padding Mask
```python
targets = torch.tensor([[1, 2, 3, 0, 0],
                        [4, 5, 0, 0, 0]])
PAD_ID = 0

# Create mask and apply to logits
pad_mask = (targets == PAD_ID)  # (2, 5) bool
logits = torch.randn(2, 5, 7)
logits_masked = logits.masked_fill(pad_mask.unsqueeze(-1), -float('inf'))
print(f"Masked shape: {logits_masked.shape}")
```

### Exercise 4: Reshape for Loss
```python
# Flatten (batch, time, vocab) → (batch*time, vocab)
logits = torch.randn(4, 10, 50)  # (batch, time, vocab)
targets = torch.randint(0, 50, (4, 10))

logits_flat = logits.reshape(-1, 50)  # (40, 50)
targets_flat = targets.reshape(-1)     # (40,)
print(f"Flat shapes: {logits_flat.shape}, {targets_flat.shape}")
```

### Exercise 5: Cat vs Stack
```python
import torch

a = torch.ones(2, 3)
b = torch.zeros(2, 3)

# What's the shape?
c1 = torch.cat([a, b], dim=0)   # ?
c2 = torch.cat([a, b], dim=1)   # ?
s1 = torch.stack([a, b], dim=0) # ?
s2 = torch.stack([a, b], dim=2) # ?

print(f"cat dim=0: {c1.shape}")
print(f"cat dim=1: {c2.shape}")
print(f"stack dim=0: {s1.shape}")
print(f"stack dim=2: {s2.shape}")
```

---

## Summary: One-Liner Reference

| Concept | Pattern | Output Shape |
|---------|---------|---------------|
| **Slice** | `x[start:stop:step]` | shape depends on indices |
| **Batch item** | `x[i]` | all dims except first |
| **Time step** | `x[:, t, :]` | (batch, features) |
| **Argmax** | `x.argmax(dim=d)` | shape without dim d |
| **Unsqueeze** | `x.unsqueeze(d)` | (shape with 1 added at d) |
| **Squeeze** | `x.squeeze(d)` | (shape with d=1 removed) |
| **Reshape** | `x.reshape(-1, C)` | (-1 inferred as batch*time) |
| **Permute** | `x.permute(p0, p1, ...)` | reordered dims |
| **Cat** | `cat([a, b], dim=d)` | (shape with growth along d) |
| **Stack** | `stack([a, b], dim=d)` | (shape with new dim at d) |
| **Masked fill** | `x.masked_fill(mask, val)` | same shape, masked vals replaced |
| **Broadcast** | `x + bias` | shape of larger tensor |

---

**You're ready! Go build awesome deep learning models!** 🚀